[package]
name = "directdesk-service"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "DirectDeskService"
path = "src/main.rs"

[dependencies]
directdesk-shared = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
windows-service = { workspace = true }

[dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_WindowsFirewall",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Storage_FileSystem",
    "Win32_System_Com",
    "Win32_System_Environment",
    "Win32_System_IO",
    "Win32_System_Ole",
    "Win32_System_Pipes",
    "Win32_System_Registry",
    "Win32_System_RemoteDesktop",
    "Win32_System_Threading",
    "Win32_System_Variant",
    "Win32_UI_WindowsAndMessaging",
]
